// Builds supabase/seed.sql from the same sample data the demo mode uses.
// Run with:  node scripts/build-seed.mjs
// (You only need this if you change public/js/demo/seed-data.js.)
import { writeFileSync } from "node:fs";
import { buildSeed } from "../public/js/demo/seed-data.js";

const { tables } = buildSeed();
// Order matters: parents before children. Logins (profiles) are created in the admin dashboard instead.
const ORDER = ["seasons", "leagues", "venues", "teams", "players", "fixtures", "frames", "breaks", "articles", "pages", "sponsors"];

const lit = (v) => {
  if (v === null || v === undefined) return "null";
  if (typeof v === "boolean" || typeof v === "number") return String(v);
  return `'${String(v).replace(/'/g, "''")}'`;
};

let sql = "-- Sample data for testing. Generated by scripts/build-seed.mjs — safe to delete later from the admin dashboard.\n";
sql += "-- Run AFTER schema.sql, in Supabase → SQL Editor.\n\nbegin;\n";
for (const name of ORDER) {
  const rows = tables[name];
  if (!rows.length) continue;
  const cols = Object.keys(rows[0]);
  sql += `\ninsert into ${name} (${cols.join(", ")}) values\n`;
  sql += rows.map((r) => `  (${cols.map((c) => lit(r[c])).join(", ")})`).join(",\n");
  sql += "\non conflict do nothing;\n";
}
sql += "\ncommit;\n";

writeFileSync(new URL("../supabase/seed.sql", import.meta.url), sql);
console.log(`Wrote supabase/seed.sql (${ORDER.map((n) => `${tables[n].length} ${n}`).join(", ")})`);
