-- ─────────────────────────────────────────────────────────────
--  THE REAL 2026-27 SEASON
--  Takes the sample league out and puts the real one in.
--  Generated by scripts/build-real-season.mjs from real-data/2026-27/.
--
--  How to run it (once):
--    1. Supabase → SQL Editor → run all of supabase/schema.sql   (it adds the bye-weeks table)
--    2. New query → paste this whole file → Run
--
--  What it REMOVES
--    · every fixture, scorecard and break in the database (all of them are sample or test results)
--    · every sample player
--    · every season except 2026-2027
--    · the sample competition draws and results, and test matches on the live scoreboard
--
--  What it KEEPS
--    · the teams, venues and leagues, with the emblems and pictures you have added
--      (only their details are brought up to date)
--    · players you added yourself, logins, news, pages, sponsors, the image library, settings and branding
--
--  What it ADDS
--    · 153 players in their 19 teams, and 155 players the old website lists without a team
--    · the CueView answers of the 17 players who have any
--    · all 162 league fixtures and the 18 bye weeks
--    · the 26 matches played so far, frame by frame (130 frames, 10 breaks)
--    · the 11 competitions of 2026-2027, without their draws
--
--  It is all one transaction: if anything goes wrong, nothing is changed.
--  Running it a second time puts the season back exactly as it is in the files —
--  so DON'T run it again once captains have started entering results on the website.
-- ─────────────────────────────────────────────────────────────
begin;

do $$ begin
  if to_regclass('public.byes') is null then
    raise exception 'Run supabase/schema.sql first (it adds the bye-weeks table), then run this file again.';
  end if;
end $$;

-- ── 1. the sample and test data comes out ─────────────────────
delete from live_matches;
delete from competition_signups;
delete from competition_matches;   -- their frames and breaks go with them
delete from competition_entries;
delete from byes;
delete from fixtures;              -- every league match; frames and breaks go with them
delete from players where id::text like '00000000-0000-4000-8000-%';
-- The home page's "player of the week" and "team of the week" were sample ones.
update settings set player_of_week_show = false, player_of_week_text = null where player_of_week_id is null;
update settings set team_of_week_show = false, team_of_week_id = null, team_of_week_text = null
  where team_of_week_text = 'A five-frame whitewash in their first home match.';

-- ── 2. one season: 2026-2027 ────────────────────────────────
insert into seasons (name, is_current) select '2026-2027', true where not exists (select 1 from seasons where name = '2026-2027');
update seasons set is_current = (name = '2026-2027') where is_current is distinct from (name = '2026-2027');
update competitions set season_id = (select id from seasons where name = '2026-2027');
delete from seasons where name <> '2026-2027';

-- ── 3. leagues, venues and teams: kept, and brought up to date ─
create temp table _leagues (name text, short_name text, slug text, sort int) on commit drop;
insert into _leagues values
  ('Victory League', 'Victory', 'victory-league', 1),
  ('Rees Memorial League', 'Rees', 'rees-memorial-league', 2);
insert into leagues (name, short_name, slug, sort)
  select r.name, r.short_name, r.slug, r.sort from _leagues r where not exists (select 1 from leagues l where l.slug = r.slug);
-- Who held each shield when the season started was sample data too: set it under Admin → Leagues.
update leagues set shield_team_id = null where id::text like '00000000-0000-4000-8000-%';

-- Two venues had stand-in names in the sample league.
update venues set name = 'Gorran Haven Snooker Club', slug = 'gorran-haven-snooker-club'
  where name = 'Gorran Haven Club' and not exists (select 1 from venues where name = 'Gorran Haven Snooker Club');
update venues set name = 'Lerryn Community Centre', slug = 'lerryn-community-centre'
  where name = 'Lerryn Memorial Hall' and not exists (select 1 from venues where name = 'Lerryn Community Centre');
create temp table _venues (name text, slug text, address text) on commit drop;
insert into _venues values
  ('Bethel Social Club', 'bethel-social-club', null),
  ('Bugle Working Mens Club', 'bugle-working-mens-club', '4 Rosevear Rd, Bugle, St Austell, PL26 8PH'),
  ('Luxulyan Memorial Institute', 'luxulyan-memorial-institute', null),
  ('Mevagissey Social Club', 'mevagissey-social-club', null),
  ('Pelynt Social Club', 'pelynt-social-club', null),
  ('St Blazey Football Club', 'st-blazey-football-club', null),
  ('St Neot Social Club', 'st-neot-social-club', null),
  ('Tregonissey Social Club', 'tregonissey-social-club', null),
  ('Gorran Haven Snooker Club', 'gorran-haven-snooker-club', null),
  ('Lerryn Community Centre', 'lerryn-community-centre', null);
insert into venues (name, slug)
  select r.name, r.slug from _venues r where not exists (select 1 from venues v where lower(v.name) = lower(r.name));
-- The sample addresses and descriptions were made up: they go (anything you have typed in yourself stays).
update venues set address = null where address like '%Placeholder Road%';
update venues set description = null where description in ('Friendly working men''s club with a full size match table.', 'Village institute hosting league snooker every week of the season.', 'Harbour-side social club with two match tables.', 'Community social club welcoming visiting teams.', 'Clubhouse snooker room at the football ground.', 'Moorland village club with a single match table.', 'Long-standing league venue with three tables.', 'Placeholder venue — edit in the admin dashboard.');
update venues v set address = r.address from _venues r where lower(v.name) = lower(r.name) and r.address is not null and nullif(v.address, '') is null;
update venues set description = 'Opening times: Monday to Thursday 7pm–11pm, Friday 7pm–midnight, Saturday midday–midnight, Sunday midday–10.30pm.'
  where name = 'Bugle Working Mens Club' and nullif(description, '') is null;

create temp table _teams (name text, league_slug text, venue text) on commit drop;
insert into _teams values
  ('Bethel A', 'victory-league', 'Bethel Social Club'),
  ('Bugle', 'victory-league', 'Bugle Working Mens Club'),
  ('Luxulyan A', 'victory-league', 'Luxulyan Memorial Institute'),
  ('Mevagissey A', 'victory-league', 'Mevagissey Social Club'),
  ('Mevagissey B', 'victory-league', 'Mevagissey Social Club'),
  ('Pelynt', 'victory-league', 'Pelynt Social Club'),
  ('St Blazey A', 'victory-league', 'St Blazey Football Club'),
  ('St Blazey B', 'victory-league', 'St Blazey Football Club'),
  ('St Neot', 'victory-league', 'St Neot Social Club'),
  ('Tregonissey A', 'victory-league', 'Tregonissey Social Club'),
  ('Bethel B', 'rees-memorial-league', 'Bethel Social Club'),
  ('Bethel C', 'rees-memorial-league', 'Bethel Social Club'),
  ('Bethel D', 'rees-memorial-league', 'Bethel Social Club'),
  ('Gorran Haven', 'rees-memorial-league', 'Gorran Haven Snooker Club'),
  ('Lerryn', 'rees-memorial-league', 'Lerryn Community Centre'),
  ('Luxulyan B', 'rees-memorial-league', 'Luxulyan Memorial Institute'),
  ('Mevagissey C', 'rees-memorial-league', 'Mevagissey Social Club'),
  ('Tregonissey B', 'rees-memorial-league', 'Tregonissey Social Club'),
  ('Tregonissey C', 'rees-memorial-league', 'Tregonissey Social Club');
insert into teams (name, slug, league_id, venue_id)
  select r.name, public.slugify(r.name), l.id, v.id from _teams r
  join leagues l on l.slug = r.league_slug join venues v on lower(v.name) = lower(r.venue)
  where not exists (select 1 from teams t where lower(t.name) = lower(r.name));
update teams t set league_id = l.id, venue_id = v.id, active = true from _teams r
  join leagues l on l.slug = r.league_slug join venues v on lower(v.name) = lower(r.venue)
  where lower(t.name) = lower(r.name) and (t.league_id is distinct from l.id or t.venue_id is distinct from v.id or t.active is not true);

-- ── 4. the players ────────────────────────────────────────────
-- "team" is empty for the players the old website lists without a team: they come in as
-- "No team at the moment" (still on the Handicaps page and in entry forms, in no squad).
-- A handicap of 0 with no handicap on the old site is listed in NOTES-from-the-old-site.md.
create temp table _players (full_name text, team text, position text, handicap int, status text, cueview jsonb, bio text) on commit drop;
insert into _players values
  ('Matt Green', 'Bethel A', 'Team Captain', 5, 'playing', '{"hand":"Right","highest_break":"78","achievement":"Winning bill Tom''s competition","ambition":"Want to hit the magic century","best_player":"Barry Macintosh when he plays","commentator":"Stephen hendry","famous_met":"Mark selby"}'::jsonb, null),
  ('Garry Stephens', 'Bethel A', 'Vice Captain', 5, 'playing', '{}'::jsonb, null),
  ('Paul Baron', 'Bethel A', 'Player', 5, 'playing', '{}'::jsonb, null),
  ('Mark Ashton', 'Bethel A', 'Player', 7, 'playing', '{}'::jsonb, null),
  ('Andy Peers', 'Bethel A', 'Player', 16, 'playing', '{}'::jsonb, null),
  ('Craig Nicholls', 'Bethel B', 'Team Captain', 30, 'playing', '{}'::jsonb, null),
  ('Neil Williams', 'Bethel B', 'Player', 30, 'playing', '{}'::jsonb, null),
  ('Matt Moore', 'Bethel B', 'Player', 35, 'playing', '{}'::jsonb, null),
  ('Roy Bayliss', 'Bethel B', 'Player', 35, 'playing', '{}'::jsonb, null),
  ('Darren Biggen', 'Bethel B', 'Vice Captain', 40, 'playing', '{}'::jsonb, null),
  ('Mark Haworth', 'Bethel B', 'Player', 40, 'playing', '{}'::jsonb, null),
  ('Terry Nicholls', 'Bethel B', 'Player', 50, 'playing', '{}'::jsonb, null),
  ('Joshua Doherty', 'Bethel B', 'Player', 50, 'playing', '{}'::jsonb, null),
  ('Martin Powell', 'Bethel C', 'Player', 25, 'playing', '{}'::jsonb, null),
  ('Howard Brett', 'Bethel C', 'Team Captain', 30, 'playing', '{}'::jsonb, null),
  ('Leigh Rosevear', 'Bethel C', 'Player', 30, 'playing', '{}'::jsonb, null),
  ('Roger Smithson', 'Bethel C', 'Player', 35, 'playing', '{"hand":"Right"}'::jsonb, null),
  ('Ben Stunell', 'Bethel C', 'Player', 35, 'playing', '{}'::jsonb, null),
  ('James Smithson', 'Bethel C', 'Vice Captain', 35, 'playing', '{}'::jsonb, null),
  ('Mike Haley', 'Bethel C', 'Player', 35, 'playing', '{}'::jsonb, null),
  ('Courtney Crockford', 'Bethel C', 'Player', 40, 'playing', '{}'::jsonb, null),
  ('Paul Smithson', 'Bethel C', 'Player', 40, 'playing', '{}'::jsonb, null),
  ('Paul Thomas', 'Bethel C', 'Player', 40, 'playing', '{}'::jsonb, null),
  ('Liam Jones', 'Bethel D', 'Player', 12, 'playing', '{}'::jsonb, null),
  ('Jason Pascoe', 'Bethel D', 'Team Captain', 21, 'playing', '{"hand":"Right"}'::jsonb, null),
  ('Geoff Hawken', 'Bethel D', 'Player', 21, 'playing', '{}'::jsonb, null),
  ('Bob Stephens', 'Bethel D', 'Player', 21, 'playing', '{}'::jsonb, null),
  ('Steve Bennallack', 'Bethel D', 'Player', 28, 'playing', '{}'::jsonb, null),
  ('Andy Sayer', 'Bethel D', 'Player', 35, 'playing', '{}'::jsonb, null),
  ('Ross McMenemy', 'Bethel D', 'Vice Captain', 40, 'playing', '{"hand":"Right","famous_met":"Andy Hicks"}'::jsonb, null),
  ('Keith Moore', 'Bugle', 'Team Captain', 25, 'playing', '{}'::jsonb, null),
  ('Colin Rundle', 'Bugle', 'Vice Captain', 35, 'playing', '{}'::jsonb, null),
  ('Dave Rundle', 'Bugle', 'Player', 18, 'playing', '{}'::jsonb, null),
  ('Jake Moore', 'Bugle', 'Player', 12, 'playing', '{}'::jsonb, null),
  ('Mark Sturtridge', 'Bugle', 'Player', 30, 'playing', '{}'::jsonb, null),
  ('Nigel Couchman', 'Bugle', 'Player', 40, 'playing', '{}'::jsonb, null),
  ('Ian Ball', 'Bugle', 'Player', 18, 'playing', '{}'::jsonb, null),
  ('Mike Williams', 'Bugle', 'Player', 50, 'playing', '{}'::jsonb, null),
  ('Ben Prynn', 'Mevagissey A', 'Team Captain', 16, 'playing', '{}'::jsonb, null),
  ('Matthew Chesterfield', 'Mevagissey A', 'Vice Captain', 25, 'playing', '{}'::jsonb, null),
  ('Matt Mills', 'Mevagissey A', 'Player', 18, 'playing', '{"hand":"Right"}'::jsonb, null),
  ('Ryan Bilson', 'Mevagissey A', 'Player', 0, 'playing', '{"hand":"Right","started":"17 and only started playing due to not playing football anymore","first_memory":"Really can''t remember.....","highest_break":"122","achievement":"Knocking in my first Century couldn''t beat the buzz!","ambition":"Singles Champion/County Champion","memorable_match":"Paul Matthews beating some guy in Rees League many moons ago! He was 52 behind with 27 on and won on the black......started 7:30 finished at 8:55.....marathon match but fair play to him","favourite_pro":"Judd Trump.......exciting to watch","commentator":"John Virgo","famous_met":"Judd Trump","bogey":"Andy Peers","best_player":"Barrie McIntosh","underrated":"Jason Cocks","funniest":"Henry McGall picking up the white thinking Barrie McIntosh had gone in off with basically all the balls open and cert to win only for Barrie to punish that mistake and win on Pink i believe....Henry wasn''t happy LOL"}'::jsonb, 'Mr Passionate'),
  ('Charlie Prynn', 'Mevagissey A', 'Player', 40, 'playing', '{}'::jsonb, null),
  ('Darren Powell', 'Mevagissey A', 'Player', 30, 'playing', '{}'::jsonb, null),
  ('Rob Blamey', 'Mevagissey A', 'Player', 45, 'playing', '{"hand":"Both","started":"35 , needed a reason to go out on tues","first_memory":"Get your hand off that table!","highest_break":"12","achievement":"Brown to black to beat M Mills league game","ambition":"Pot more blacks","memorable_match":"Rich v lurch","favourite_pro":"Tiger woods","commentator":"Peter Alis","famous_met":"Joe davis","bogey":"Myself","best_player":"Not sure yet","underrated":"?","funniest":"?"}'::jsonb, null),
  ('James Tomlinson', 'Mevagissey A', 'Player', 30, 'playing', '{}'::jsonb, null),
  ('Scott Mills', 'Mevagissey A', 'Player', 40, 'playing', '{}'::jsonb, null),
  ('Andre Koranteng', 'Mevagissey A', 'Player', 0, 'playing', '{}'::jsonb, null),
  ('James Prynn', 'Mevagissey A', 'Player', 60, 'playing', '{}'::jsonb, null),
  ('Ian Latham', 'Mevagissey A', 'Player', 40, 'playing', '{}'::jsonb, null),
  ('Neil Parker', 'Mevagissey B', 'Player', 50, 'playing', '{}'::jsonb, null),
  ('Mark Gregory', 'Mevagissey B', 'Team Captain', 25, 'playing', '{}'::jsonb, null),
  ('Matt Rowe', 'Mevagissey B', 'Vice Captain', 35, 'playing', '{}'::jsonb, null),
  ('Dave Kendall', 'Mevagissey B', 'Player', 30, 'playing', '{}'::jsonb, null),
  ('Nathan Shaw', 'Mevagissey B', 'Player', 18, 'playing', '{}'::jsonb, null),
  ('Ben Rothwell', 'Mevagissey B', 'Player', 25, 'playing', '{}'::jsonb, null),
  ('Pete Chambers', 'Mevagissey B', 'Player', 0, 'playing', '{}'::jsonb, null),
  ('Peter Harford', 'Mevagissey C', 'Player', 0, 'playing', '{}'::jsonb, null),
  ('Benjamin Baker', 'Mevagissey C', 'Player', 45, 'playing', '{}'::jsonb, null),
  ('Richard Lakeman', 'Mevagissey C', 'Player', 30, 'playing', '{}'::jsonb, null),
  ('John Stephens', 'Mevagissey C', 'Player', 40, 'playing', '{}'::jsonb, null),
  ('Andrew Kitt', 'Mevagissey C', 'Player', 35, 'playing', '{"highest_break":"8","achievement":"Representing England Choir Boys Team","ambition":"Get a break in double figures","famous_met":"Chris Brown"}'::jsonb, null),
  ('Adrian Evans', 'Mevagissey C', 'Team Captain', 40, 'playing', '{}'::jsonb, null),
  ('Glyn Tamblin', 'Mevagissey C', 'Vice Captain', 50, 'playing', '{}'::jsonb, null),
  ('Oliver Watson', 'Mevagissey C', 'Player', 55, 'playing', '{}'::jsonb, null),
  ('Mark Ferguson', 'Mevagissey C', 'Player', 40, 'playing', '{}'::jsonb, null),
  ('Richard Tamblin', 'Mevagissey C', 'Player', 40, 'playing', '{}'::jsonb, null),
  ('Joe Chesterfield', 'Mevagissey C', 'Player', 45, 'playing', '{}'::jsonb, null),
  ('Phil Ormond', 'Pelynt', 'Player', 16, 'playing', '{}'::jsonb, null),
  ('John Daniell', 'Pelynt', 'Team Captain', 35, 'playing', '{}'::jsonb, null),
  ('Len Flower', 'Pelynt', 'Vice Captain', 21, 'playing', '{}'::jsonb, null),
  ('Jamie Daniell', 'Pelynt', 'Player', 10, 'playing', '{}'::jsonb, null),
  ('Paul Woodman', 'Pelynt', 'Player', 25, 'playing', '{}'::jsonb, null),
  ('Richard Broad', 'Pelynt', 'Player', 21, 'playing', '{}'::jsonb, null),
  ('Billy Vigus', 'St Blazey A', 'Team Captain', 30, 'playing', '{}'::jsonb, null),
  ('Chris Brown', 'St Blazey A', 'Vice Captain', 16, 'playing', '{}'::jsonb, null),
  ('Darren Roberts', 'St Blazey A', 'Player', 25, 'playing', '{}'::jsonb, null),
  ('Martin Richards', 'St Blazey A', 'Player', 40, 'playing', '{}'::jsonb, null),
  ('George Taylor', 'St Blazey A', 'Player', 35, 'playing', '{}'::jsonb, null),
  ('Stuart Dewings', 'St Blazey A', 'Player', 30, 'playing', '{}'::jsonb, null),
  ('Kyle Masters', 'St Blazey A', 'Player', 30, 'playing', '{}'::jsonb, null),
  ('Ian Millward', 'St Blazey B', 'Player', 16, 'playing', '{}'::jsonb, null),
  ('Liam Reynolds', 'St Blazey B', 'Player', 16, 'playing', '{}'::jsonb, null),
  ('Ryan Orchard', 'St Blazey B', 'Player', 21, 'playing', '{}'::jsonb, null),
  ('Paul Roberts', 'St Blazey B', 'Player', 40, 'playing', '{}'::jsonb, null),
  ('Joshua Bristow', 'St Blazey B', 'Team Captain', 12, 'playing', '{}'::jsonb, null),
  ('Clive Stuthridge', 'St Blazey B', 'Vice Captain', 21, 'playing', '{"hand":"Left","famous_met":"Judd Trump"}'::jsonb, null),
  ('Gavin Dyche', 'St Blazey B', 'Player', 16, 'playing', '{}'::jsonb, null),
  ('Mark Nicolas', 'St Neot', 'Player', 35, 'playing', '{}'::jsonb, null),
  ('Nigel Collins', 'St Neot', 'Player', 21, 'playing', '{}'::jsonb, null),
  ('Mark Story', 'St Neot', 'Player', 25, 'playing', '{}'::jsonb, null),
  ('Andrew Tamblyn', 'St Neot', 'Player', 25, 'playing', '{}'::jsonb, null),
  ('Steve Courts', 'St Neot', 'Team Captain', 7, 'playing', '{}'::jsonb, null),
  ('Chris Perring', 'St Neot', 'Player', 40, 'playing', '{}'::jsonb, null),
  ('Darran Lock', 'St Neot', 'Vice Captain', -14, 'playing', '{}'::jsonb, null),
  ('Anthony Maddams', 'St Neot', 'Player', 45, 'playing', '{}'::jsonb, null),
  ('Darren OShea', 'St Neot', 'Player', 35, 'playing', '{}'::jsonb, null),
  ('Richard Pearson', 'Tregonissey A', 'Player', 7, 'playing', '{"hand":"Left","started":"11, Saturday mornings, something to do","first_memory":"Watching Steve Davis and Dennis Taylor''s black ball finish at the World Champs","highest_break":"118","achievement":"Winning nearly every league in Cornwall, and getting the highest break in the Mining League the year we won it","ambition":"Loads, but age is against me, I suppose to do well or win the county singles","memorable_match":"Far to many to name","favourite_pro":"Ronnie O''Sulllivan, pure genius","commentator":"Stephen Hendry and Ken Doherty","famous_met":"Ronnie O''Sullivan, Jimmy White, Steve Davis, Stephen Hendry, Paul Hunter, Matthew Stephens, basically most of them, I have been lucky to have played a lot of them as well","bogey":"Don''t really have one","best_player":"Currently - probably Andrew Best, but in the past Barrie McIntosh","underrated":"Me!","funniest":"Lights went out in match, iron was put down, lights back on, carried on ironing the table to find out the floor on which the iron was on was full of dirt, ironed the cloth and melted the cloth"}'::jsonb, null),
  ('Geoff Merriman', 'Tregonissey A', 'Team Captain', 21, 'playing', '{}'::jsonb, null),
  ('Andrew Gooch', 'Tregonissey A', 'Vice Captain', 5, 'playing', '{}'::jsonb, null),
  ('Jason Cocks', 'Tregonissey A', 'Player', 5, 'playing', '{}'::jsonb, null),
  ('Kevin Harris', 'Tregonissey A', 'Player', 21, 'playing', '{}'::jsonb, null),
  ('Mark Poulson', 'Tregonissey A', 'Player', 21, 'playing', '{}'::jsonb, null),
  ('Dan Allen', 'Tregonissey A', 'Player', 25, 'playing', '{}'::jsonb, null),
  ('Jowan Truman', 'Tregonissey B', 'Team Captain', 30, 'playing', '{}'::jsonb, null),
  ('Nathan Taylor', 'Tregonissey B', 'Vice Captain', 45, 'playing', '{}'::jsonb, null),
  ('Ryan Taylor', 'Tregonissey B', 'Player', 60, 'playing', '{}'::jsonb, null),
  ('Josh Pollard', 'Tregonissey B', 'Player', 50, 'playing', '{}'::jsonb, null),
  ('Marc Luczynski', 'Tregonissey B', 'Player', 35, 'playing', '{}'::jsonb, null),
  ('Chris Witcombe', 'Tregonissey B', 'Player', 50, 'playing', '{}'::jsonb, null),
  ('Mark Craddock', 'Tregonissey B', 'Player', 45, 'playing', '{}'::jsonb, null),
  ('Graham Taylor', 'Tregonissey B', 'Player', 18, 'playing', '{}'::jsonb, null),
  ('Amanda Fleming', 'Tregonissey C', 'Team Captain', 60, 'playing', '{}'::jsonb, null),
  ('Kelly McMullen', 'Tregonissey C', 'Vice Captain', 60, 'playing', '{}'::jsonb, null),
  ('Mark Richards', 'Tregonissey C', 'Player', 30, 'playing', '{}'::jsonb, null),
  ('Dave Tregale', 'Tregonissey C', 'Player', 40, 'playing', '{}'::jsonb, null),
  ('Lucy Harrison', 'Tregonissey C', 'Player', 50, 'playing', '{}'::jsonb, null),
  ('Ellie Potter', 'Tregonissey C', 'Player', 60, 'playing', '{}'::jsonb, null),
  ('Lynn Kearns', 'Tregonissey C', 'Player', 60, 'playing', '{}'::jsonb, null),
  ('Darren Elliott', 'Tregonissey C', 'Player', 40, 'playing', '{}'::jsonb, null),
  ('Edward Barkhuysen', 'Gorran Haven', 'Player', 0, 'playing', '{}'::jsonb, null),
  ('Matt Fox', 'Gorran Haven', 'Player', 16, 'playing', '{}'::jsonb, null),
  ('Lee McKinstry', 'Gorran Haven', 'Team Captain', 21, 'playing', '{"hand":"Right","started":"7 ish and Christmas present snooker table","first_memory":"Black ball final 1985","highest_break":"45","achievement":"Scoring 27 points against Andy Hicks!!","ambition":"50 break","memorable_match":"1985 final","favourite_pro":"Ronnie, no need to say why!","commentator":"John Virgo","famous_met":"Steve Davis","bogey":"No one springs to mind","best_player":"Not sure yet","underrated":"Not sure of that either","funniest":"Andy Redalls impossible shot at Tregonnissey"}'::jsonb, null),
  ('Steve Williams', 'Gorran Haven', 'Vice Captain', 50, 'playing', '{}'::jsonb, null),
  ('Rob Bunney', 'Gorran Haven', 'Player', 45, 'playing', '{}'::jsonb, null),
  ('Dan Pascoe', 'Gorran Haven', 'Player', 45, 'playing', '{}'::jsonb, null),
  ('Warren Ball', 'Gorran Haven', 'Player', 35, 'playing', '{}'::jsonb, null),
  ('Terry Mills', 'Gorran Haven', 'Player', 35, 'playing', '{}'::jsonb, null),
  ('James Towsey', 'Gorran Haven', 'Player', 50, 'playing', '{}'::jsonb, null),
  ('Simon Yeo', 'Lerryn', 'Player', 0, 'playing', '{}'::jsonb, null),
  ('Terry Middleton', 'Lerryn', 'Team Captain', 45, 'playing', '{}'::jsonb, null),
  ('Les Shakespeare', 'Lerryn', 'Vice Captain', 30, 'playing', '{}'::jsonb, null),
  ('John Hancock', 'Lerryn', 'Player', 50, 'playing', '{}'::jsonb, null),
  ('David Vipond', 'Lerryn', 'Player', 55, 'playing', '{}'::jsonb, null),
  ('Graham Hoskin', 'Lerryn', 'Player', 40, 'playing', '{}'::jsonb, null),
  ('James Stephens', 'Lerryn', 'Player', 40, 'playing', '{}'::jsonb, null),
  ('Gary Spencer', 'Luxulyan A', 'Team Captain', -5, 'playing', '{"hand":"Right","started":"15 - Because I wasn''t allowed to play earlier at Bugle WMC at that time.","first_memory":"Losing on the black in my first ever league game in the Ree''s League when stepping in last minute to make up the numbers","highest_break":"Solo practice 145 (On video at Bugle Club witnessed on video but never recieved the footage!)140 Total Clearance vs an opponent, 122 Total Clearance and x3 Matchplay tons 101, 102 & 106 to date. Nationals Highest for Cornwall 89.","achievement":"3 x Matchplay tons (102 in 2009 League match and two in 2025/26 season, one in the county dbls semi-final (101) and the other in the East vs West away leg (106 ). , beating Andy hicks in an exhibition, 140TC vs Andrew Best in practice, making 145 in solo practice, representing Cornwall in the Nationals in 2025/26 season (Team highest break 89), County Team & Doubles trophies (x 2) , Victory League seasons 2009 & 2018/19 winning multiple trophy''s from team ones, to dbls and individuals along with many successful seasons in between. Winning the County Highest break Trophy 25/26 (101). Winning the league rankings twice, St Blazey & District League Snooker Shootout winner x 2 from two..","ambition":"A 147, League Singles (x2 finalist) & County Singles (x 2 Semi-Finalist only 1 ball away from the final the 1st time).","memorable_match":"Ronnie v Higgins when Higgins won by a single frame when Ronnie was playing sublime and Higgins not only matched him but won the final. Unsure on the year, but remember watching it till the end!","favourite_pro":"Ronnie","commentator":"Joe Perry/Hendry","famous_met":"Ronnie, Judd, Mark Williams (met) and luckily plenty more","bogey":"Don''t really have one","best_player":"Darren Lock/Me/Andrew Best","underrated":"Garry Stephens","funniest":"Mo climbing under the matchtable whilst a game was in progress to get his ball back from the 2nd table. Only Mo!"}'::jsonb, null),
  ('Andrew Best', 'Luxulyan A', 'Player', 0, 'playing', '{}'::jsonb, null),
  ('Paul Sturtridge', 'Luxulyan A', 'Player', 16, 'playing', '{}'::jsonb, null),
  ('Justin Oxenham', 'Luxulyan A', 'Vice Captain', 21, 'playing', '{}'::jsonb, null),
  ('Ian Powell', 'Luxulyan A', 'Player', 25, 'playing', '{}'::jsonb, null),
  ('Harrison Burdon', 'Luxulyan A', 'Player', 30, 'playing', '{}'::jsonb, null),
  ('Simon Taylor', 'Luxulyan A', 'Player', 35, 'playing', '{}'::jsonb, null),
  ('Keiran Pearce', 'Luxulyan A', 'Player', 40, 'playing', '{}'::jsonb, null),
  ('Simon Johnson', 'Luxulyan B', 'Player', 30, 'playing', '{}'::jsonb, null),
  ('Kyle Bennetts', 'Luxulyan B', 'Player', 30, 'playing', '{}'::jsonb, null),
  ('Neil Webb', 'Luxulyan B', 'Player', 35, 'playing', '{}'::jsonb, null),
  ('Steve Vicary', 'Luxulyan B', 'Team Captain', 40, 'playing', '{}'::jsonb, null),
  ('Keith Remphry', 'Luxulyan B', 'Player', 45, 'playing', '{}'::jsonb, null),
  ('Kevin Spencer', 'Luxulyan B', 'Vice Captain', 50, 'playing', '{}'::jsonb, null),
  ('Tony Grose', 'Luxulyan B', 'Player', 50, 'playing', '{}'::jsonb, null),
  ('Kenanne Burt', 'Luxulyan B', 'Player', 50, 'playing', '{}'::jsonb, null),
  ('Chris Austin', 'Luxulyan B', 'Player', 50, 'playing', '{}'::jsonb, null),
  ('Abi Edwards', null, 'Player', 60, 'no_team', '{}'::jsonb, null),
  ('Adrian Bowyer', null, 'Player', 45, 'no_team', '{}'::jsonb, null),
  ('Adrian Dyche', null, 'Player', 35, 'no_team', '{}'::jsonb, null),
  ('Aiden Craddock', null, 'Player', 35, 'no_team', '{}'::jsonb, null),
  ('Alan Meades', null, 'Player', 0, 'no_team', '{}'::jsonb, null),
  ('Andrew Pollard', null, 'Player', 60, 'no_team', '{}'::jsonb, null),
  ('Andy Cooke', null, 'Player', 45, 'no_team', '{}'::jsonb, null),
  ('Andy Garside', null, 'Player', 60, 'no_team', '{}'::jsonb, null),
  ('Andy Parnell', null, 'Player', 40, 'no_team', '{}'::jsonb, null),
  ('Andy Pearce', null, 'Player', 0, 'no_team', '{}'::jsonb, null),
  ('Andy Ridgeman', null, 'Player', -7, 'no_team', '{}'::jsonb, null),
  ('Antony Cornwall', null, 'Player', 60, 'no_team', '{}'::jsonb, null),
  ('Antony Harrison', null, 'Player', 40, 'no_team', '{}'::jsonb, null),
  ('Barrie McIntosh', null, 'Player', -7, 'no_team', '{}'::jsonb, null),
  ('Brian Green', null, 'Player', 45, 'no_team', '{}'::jsonb, null),
  ('Carol Stephens', null, 'Player', 50, 'no_team', '{}'::jsonb, null),
  ('Charles McMiram', null, 'Player', 55, 'no_team', '{}'::jsonb, null),
  ('Chris Cocks', null, 'Player', 60, 'no_team', '{}'::jsonb, null),
  ('Chris Edwards', null, 'Player', 60, 'no_team', '{}'::jsonb, null),
  ('Chris Hazell', null, 'Player', 60, 'no_team', '{}'::jsonb, null),
  ('Chris Ireland', null, 'Player', 55, 'no_team', '{}'::jsonb, null),
  ('Chris Kendall', null, 'Player', 16, 'no_team', '{}'::jsonb, null),
  ('Chris Leonard', null, 'Player', 60, 'no_team', '{}'::jsonb, null),
  ('Chris McAvoy', null, 'Player', 0, 'no_team', '{}'::jsonb, null),
  ('Chris Mitchell', null, 'Player', 25, 'no_team', '{}'::jsonb, null),
  ('Chris Morford', null, 'Player', 18, 'no_team', '{}'::jsonb, null),
  ('Chris Stephenson', null, 'Player', 10, 'no_team', '{}'::jsonb, null),
  ('Claire Cortis', null, 'Player', 60, 'no_team', '{}'::jsonb, null),
  ('Craig Wherry', null, 'Player', 40, 'no_team', '{}'::jsonb, null),
  ('Damian Knight', null, 'Player', 50, 'no_team', '{}'::jsonb, null),
  ('Damien Rowe', null, 'Player', 60, 'no_team', '{}'::jsonb, null),
  ('Dan Tynan', null, 'Player', 0, 'no_team', '{}'::jsonb, null),
  ('Daniel Parmenter', null, 'Player', 60, 'no_team', '{}'::jsonb, null),
  ('Darwin Fitz', null, 'Player', 50, 'no_team', '{}'::jsonb, null),
  ('Dave McClaren', null, 'Player', 45, 'no_team', '{}'::jsonb, null),
  ('Dave McLaren', null, 'Player', 0, 'no_team', '{}'::jsonb, null),
  ('Dave Morshead', null, 'Player', 40, 'no_team', '{}'::jsonb, null),
  ('Dave Willis', null, 'Player', 0, 'no_team', '{}'::jsonb, null),
  ('David Chivers', null, 'Player', 30, 'no_team', '{}'::jsonb, null),
  ('David Grose', null, 'Player', 16, 'no_team', '{}'::jsonb, null),
  ('David Patton', null, 'Player', 30, 'no_team', '{}'::jsonb, null),
  ('David Roberts', null, 'Player', 60, 'no_team', '{}'::jsonb, null),
  ('Dayle Dyche', null, 'Player', 30, 'no_team', '{}'::jsonb, null),
  ('Didi Coates', null, 'Player', 60, 'no_team', '{}'::jsonb, null),
  ('Gareth Grimshaw', null, 'Player', 55, 'no_team', '{}'::jsonb, null),
  ('Gary Moore', null, 'Player', 45, 'no_team', '{}'::jsonb, null),
  ('Gary Stocks', null, 'Player', 45, 'no_team', '{}'::jsonb, null),
  ('Geoff Hayhurst', null, 'Player', 50, 'no_team', '{}'::jsonb, null),
  ('George Lory', null, 'Player', 35, 'no_team', '{}'::jsonb, null),
  ('Gerry Markwell', null, 'Player', 25, 'no_team', '{}'::jsonb, null),
  ('Graham Goode', null, 'Player', 50, 'no_team', '{}'::jsonb, null),
  ('Graham Rosevear', null, 'Player', 50, 'no_team', '{}'::jsonb, null),
  ('Guy Buckle', null, 'Player', 30, 'no_team', '{}'::jsonb, null),
  ('Ian Hawke', null, 'Player', 10, 'no_team', '{}'::jsonb, null),
  ('Ian Hinde', null, 'Player', 40, 'no_team', '{}'::jsonb, null),
  ('Ivan Hancocks', null, 'Player', 30, 'no_team', '{}'::jsonb, null),
  ('Jackie Hancock', null, 'Player', 55, 'no_team', '{}'::jsonb, null),
  ('James Beeches', null, 'Player', 60, 'no_team', '{}'::jsonb, null),
  ('James Holmes', null, 'Player', 30, 'no_team', '{}'::jsonb, null),
  ('James Popplewell', null, 'Player', 7, 'no_team', '{"hand":"Left","started":"13 years old due to football injury.","first_memory":"Playing with bamboo sticks & marbles on the dining room table with cushions made from telephone directories !"}'::jsonb, null),
  ('James Raggatt', null, 'Player', 0, 'no_team', '{}'::jsonb, null),
  ('Jamie Hobbs', null, 'Player', 45, 'no_team', '{}'::jsonb, null),
  ('Jason Best', null, 'Player', 40, 'no_team', '{}'::jsonb, null),
  ('Jason Biggen', null, 'Player', 50, 'no_team', '{}'::jsonb, null),
  ('Jason Hill', null, 'Player', 12, 'no_team', '{}'::jsonb, null),
  ('Jason Prynn', null, 'Player', 60, 'no_team', '{}'::jsonb, null),
  ('Jason Simmons', null, 'Player', 0, 'no_team', '{}'::jsonb, null),
  ('Jayden Bounsall', null, 'Player', 60, 'no_team', '{}'::jsonb, null),
  ('Jim Tamblin', null, 'Player', 60, 'no_team', '{}'::jsonb, null),
  ('John Bates', null, 'Player', 12, 'no_team', '{}'::jsonb, null),
  ('John Rosevear', null, 'Player', 45, 'no_team', '{}'::jsonb, null),
  ('John Wilson', null, 'Player', 40, 'no_team', '{}'::jsonb, null),
  ('John Wilton', null, 'Player', 35, 'no_team', '{}'::jsonb, null),
  ('Justin Hooley', null, 'Player', 30, 'no_team', '{}'::jsonb, null),
  ('Justin Pusey', null, 'Player', 55, 'no_team', '{}'::jsonb, null),
  ('Keith Armitage', null, 'Player', 25, 'no_team', '{}'::jsonb, null),
  ('Kieran Clemes', null, 'Player', 35, 'no_team', '{"hand":"Right","started":"24, always interested me. Played pool before that.","first_memory":"Sneakily watching it on my first TV when should of been asleep. I was around 9 or 10.","highest_break":"48","achievement":"So far, having a good first season.","ambition":"Oh yes.","memorable_match":"Ronnies 1000th Century, Final between Dennis Taylor and Steve Davis where they both kept bottling the black on the deciding frame.","favourite_pro":"Ronnie of course. Although Hurricane Higgins was an interesting player to watch.","commentator":"Dennis Taylor.","best_player":"Don''t know enough of our Rees League players yet but I''m going to say Rocky Reynolds.","underrated":"Me!!","funniest":"Potting the green ball when the yellow was still on the table.. more annoying than funny."}'::jsonb, null),
  ('Lee Hobbs', null, 'Player', 40, 'no_team', '{}'::jsonb, null),
  ('Lee Oxenham', null, 'Player', 0, 'no_team', '{}'::jsonb, null),
  ('Leighton Varcoe', null, 'Player', 25, 'no_team', '{}'::jsonb, null),
  ('Leon Collard', null, 'Player', 25, 'no_team', '{}'::jsonb, null),
  ('Liam Johns', null, 'Player', 35, 'no_team', '{}'::jsonb, null),
  ('Louise Winterburn', null, 'Player', 60, 'no_team', '{}'::jsonb, null),
  ('Luke Kennedy', null, 'Player', 45, 'no_team', '{}'::jsonb, null),
  ('Malcolm Hill', null, 'Player', 45, 'no_team', '{}'::jsonb, null),
  ('Mark Cockayne', null, 'Player', 35, 'no_team', '{"hand":"Right","started":"13 - Had a keen interest in pool and wanted to try snooker, 15 years on and I''m still no good at either","first_memory":"Never being allowed in the Snooker room at Tywardreath RBL","highest_break":"Have I ever had a 30 in the league?","achievement":"Rees League Winners","memorable_match":"Andrew Kitt losing at Gorran after scoring 75 points.","famous_met":"Ronnie, met at Q Bar Exhibition","best_player":"Billy Vigus"}'::jsonb, null),
  ('Mark Sullivan', null, 'Player', 40, 'no_team', '{}'::jsonb, null),
  ('Mark Wherry', null, 'Player', 60, 'no_team', '{}'::jsonb, null),
  ('Martin Insted', null, 'Player', 55, 'no_team', '{}'::jsonb, null),
  ('Martin Isted', null, 'Player', 55, 'no_team', '{}'::jsonb, null),
  ('Martin Kitt', null, 'Player', 0, 'no_team', '{}'::jsonb, null),
  ('Martin Knight', null, 'Player', 16, 'no_team', '{"hand":"Left","started":"24. Because my mates all player in the snooker league.","first_memory":"The Graham dott Peter Ebdon marathon final.","highest_break":"67","achievement":"Winning the victory league 4 years in a row.","ambition":"No.","memorable_match":"Probably James cahil beating Ronnie. That was a massive shock.","favourite_pro":"Mark Selby because of his pool background and I like the way he never gives up he never knows when he is beaten.","commentator":"John virgo","famous_met":"Mark Selby and Mark Williams","bogey":"Don''t really have one. If I had to choose the possibly Matt green from bethel","best_player":"Barrie McIntosh without a doubt!","underrated":"Wouldn''t say he is under-rated but Jason cocks the man doesn''t miss when he''s playing well.","funniest":"Me when I decided to pot a colour instead of a red lol"}'::jsonb, null),
  ('Martin McGurrell', null, 'Player', 50, 'no_team', '{}'::jsonb, null),
  ('Matt Pearce', null, 'Player', 50, 'no_team', '{}'::jsonb, null),
  ('Matt Vessey', null, 'Player', 7, 'no_team', '{}'::jsonb, null),
  ('Matt Woodward', null, 'Player', 16, 'no_team', '{}'::jsonb, null),
  ('Matthew Pearce', null, 'Player', 50, 'no_team', '{}'::jsonb, null),
  ('Michael Delaney', null, 'Player', 40, 'no_team', '{}'::jsonb, null),
  ('Michaela Edwards', null, 'Player', 60, 'no_team', '{}'::jsonb, null),
  ('Micky Meares', null, 'Player', 25, 'no_team', '{}'::jsonb, null),
  ('Mike Byard', null, 'Player', 0, 'no_team', '{}'::jsonb, null),
  ('Mike Hancock', null, 'Player', 60, 'no_team', '{}'::jsonb, null),
  ('Mike Hooley', null, 'Player', 40, 'no_team', '{}'::jsonb, null),
  ('Mike Moreland', null, 'Player', 40, 'no_team', '{}'::jsonb, null),
  ('Mike Truscott', null, 'Player', 60, 'no_team', '{}'::jsonb, null),
  ('Mo Rescorla', null, 'Player', 40, 'no_team', '{}'::jsonb, null),
  ('Mo Roscorla', null, 'Player', 60, 'no_team', '{}'::jsonb, null),
  ('Natalie Rosevear', null, 'Player', 60, 'no_team', '{}'::jsonb, null),
  ('Nick Ferguson', null, 'Player', 30, 'no_team', '{}'::jsonb, null),
  ('Nick Madin', null, 'Player', 55, 'no_team', '{}'::jsonb, null),
  ('Nigel Doble', null, 'Player', 18, 'no_team', '{}'::jsonb, null),
  ('Nigel Emms', null, 'Player', 25, 'no_team', '{}'::jsonb, null),
  ('Oliver Rounsevell', null, 'Player', 40, 'no_team', '{}'::jsonb, null),
  ('Owen Simpson', null, 'Player', 30, 'no_team', '{}'::jsonb, null),
  ('Paul Simpson', null, 'Player', 50, 'no_team', '{}'::jsonb, null),
  ('Paul Williams', null, 'Player', 0, 'no_team', '{}'::jsonb, null),
  ('Peter Bate', null, 'Player', 35, 'no_team', '{}'::jsonb, null),
  ('Phil Hooley', null, 'Player', 35, 'no_team', '{}'::jsonb, null),
  ('Phil Johns', null, 'Player', 60, 'no_team', '{}'::jsonb, null),
  ('Phil Staley', null, 'Player', 60, 'no_team', '{}'::jsonb, null),
  ('Rich McCormack', null, 'Player', 60, 'no_team', '{}'::jsonb, null),
  ('Rich Wilkinson', null, 'Player', 35, 'no_team', '{}'::jsonb, null),
  ('Richard Allen', null, 'Player', 60, 'no_team', '{}'::jsonb, null),
  ('Richard Bolt', null, 'Player', 30, 'no_team', '{}'::jsonb, null),
  ('Richard Holmes', null, 'Player', 60, 'no_team', '{}'::jsonb, null),
  ('Richard Jenkins', null, 'Player', 60, 'no_team', '{}'::jsonb, null),
  ('Richard Opie', null, 'Player', 16, 'no_team', '{}'::jsonb, null),
  ('Richard Ware', null, 'Player', 0, 'no_team', '{}'::jsonb, null),
  ('Richard Wilkinson', null, 'Player', 35, 'no_team', '{}'::jsonb, null),
  ('Rob Garside', null, 'Player', 50, 'no_team', '{}'::jsonb, null),
  ('Robert Cresswell', null, 'Player', 50, 'no_team', '{}'::jsonb, null),
  ('Robert Gascogne', null, 'Player', 0, 'no_team', '{}'::jsonb, null),
  ('Robert Maddams', null, 'Player', 0, 'no_team', '{}'::jsonb, null),
  ('Robin Pearce', null, 'Player', 55, 'no_team', '{}'::jsonb, null),
  ('Ryan Stephens', null, 'Player', 50, 'no_team', '{}'::jsonb, null),
  ('Ryan Tonkin', null, 'Player', 0, 'no_team', '{}'::jsonb, null),
  ('Sam Couchman', null, 'Player', 60, 'no_team', '{}'::jsonb, null),
  ('Sarah Franks', null, 'Player', 60, 'no_team', '{}'::jsonb, null),
  ('Shaun Strickland', null, 'Player', 60, 'no_team', '{}'::jsonb, null),
  ('Simon Garrington', null, 'Player', 40, 'no_team', '{}'::jsonb, null),
  ('Simon OShea', null, 'Player', 55, 'no_team', '{}'::jsonb, null),
  ('Stacey Hancock', null, 'Player', 45, 'no_team', '{}'::jsonb, null),
  ('Steve Knight', null, 'Player', 0, 'no_team', '{}'::jsonb, null),
  ('Stuart Bell', null, 'Player', 60, 'no_team', '{}'::jsonb, null),
  ('Stuart Cundy', null, 'Player', 30, 'no_team', '{}'::jsonb, null),
  ('Stuart Giles', null, 'Player', 35, 'no_team', '{"hand":"Right","started":"26","achievement":"Winning Rees league"}'::jsonb, null),
  ('Tim Blamey', null, 'Player', 50, 'no_team', '{}'::jsonb, null),
  ('Tom Hawken', null, 'Player', 0, 'no_team', '{}'::jsonb, null),
  ('Tony Farrant', null, 'Player', 0, 'no_team', '{}'::jsonb, null),
  ('Trevor Pearce', null, 'Player', 0, 'no_team', '{}'::jsonb, null),
  ('Tyrone Stephens', null, 'Player', 18, 'no_team', '{}'::jsonb, null),
  ('Victoria Rollings', null, 'Player', 60, 'no_team', '{}'::jsonb, null),
  ('Walter Courtis', null, 'Player', 40, 'no_team', '{}'::jsonb, null),
  ('Wayne George', null, 'Player', 40, 'no_team', '{}'::jsonb, null),
  ('Wayne Jordon', null, 'Player', 35, 'no_team', '{}'::jsonb, null);
-- Anyone already there under the same name (added by hand) is kept and brought up to date;
-- their own CueView and bio are left alone if they have any.
update players p set team_id = t.id, position = r.position, handicap = r.handicap, status = r.status,
    cueview = case when p.cueview = '{}'::jsonb then r.cueview else p.cueview end, bio = coalesce(nullif(p.bio, ''), r.bio), needs_review = false
  from _players r left join teams t on lower(t.name) = lower(r.team)
  where lower(p.full_name) = lower(r.full_name);
insert into players (full_name, team_id, position, handicap, status, cueview, bio)
  select r.full_name, t.id, r.position, r.handicap, r.status, r.cueview, r.bio
  from _players r left join teams t on lower(t.name) = lower(r.team)
  where not exists (select 1 from players p where lower(p.full_name) = lower(r.full_name))
  order by r.full_name;

-- ── 5. the fixtures ───────────────────────────────────────────
create temp table _fixtures (code text, league_slug text, day date, kick_off time, home text, away text, venue text, status text) on commit drop;
insert into _fixtures values
  ('2627-01', 'victory-league', '2026-09-22', '19:30', 'Bugle', 'Mevagissey B', 'Bugle Working Mens Club', 'approved'),
  ('2627-02', 'victory-league', '2026-09-22', '19:30', 'Mevagissey A', 'Bethel A', 'Mevagissey Social Club', 'approved'),
  ('2627-03', 'victory-league', '2026-09-22', '19:30', 'St Blazey A', 'St Blazey B', 'St Blazey Football Club', 'approved'),
  ('2627-04', 'victory-league', '2026-09-22', '19:30', 'Tregonissey A', 'Luxulyan A', 'Tregonissey Social Club', 'approved'),
  ('2627-05', 'victory-league', '2026-09-22', '19:30', 'Pelynt', 'St Neot', 'Pelynt Social Club', 'approved'),
  ('2627-06', 'rees-memorial-league', '2026-09-22', '19:30', 'Bethel D', 'Bethel C', 'Bethel Social Club', 'approved'),
  ('2627-07', 'rees-memorial-league', '2026-09-22', '19:30', 'Bethel B', 'Mevagissey C', 'Bethel Social Club', 'approved'),
  ('2627-08', 'rees-memorial-league', '2026-09-22', '19:30', 'Gorran Haven', 'Lerryn', 'Gorran Haven Snooker Club', 'approved'),
  ('2627-09', 'rees-memorial-league', '2026-09-22', '19:30', 'Luxulyan B', 'Tregonissey B', 'Luxulyan Memorial Institute', 'approved'),
  ('2627-10', 'victory-league', '2026-09-29', '19:30', 'St Neot', 'Bugle', 'St Neot Social Club', 'approved'),
  ('2627-11', 'victory-league', '2026-09-29', '19:30', 'Bethel A', 'Pelynt', 'Bethel Social Club', 'approved'),
  ('2627-12', 'victory-league', '2026-09-29', '19:30', 'St Blazey B', 'Mevagissey A', 'St Blazey Football Club', 'approved'),
  ('2627-13', 'victory-league', '2026-09-29', '19:30', 'Luxulyan A', 'St Blazey A', 'Luxulyan Memorial Institute', 'approved'),
  ('2627-14', 'victory-league', '2026-09-29', '19:30', 'Mevagissey B', 'Tregonissey A', 'Mevagissey Social Club', 'approved'),
  ('2627-15', 'rees-memorial-league', '2026-09-29', '19:30', 'Tregonissey B', 'Bethel D', 'Tregonissey Social Club', 'approved'),
  ('2627-16', 'rees-memorial-league', '2026-09-29', '19:30', 'Mevagissey C', 'Luxulyan B', 'Mevagissey Social Club', 'approved'),
  ('2627-17', 'rees-memorial-league', '2026-09-29', '19:30', 'Tregonissey C', 'Bethel B', 'Tregonissey Social Club', 'approved'),
  ('2627-18', 'rees-memorial-league', '2026-09-29', '19:30', 'Bethel C', 'Gorran Haven', 'Bethel Social Club', 'approved'),
  ('2627-19', 'victory-league', '2026-10-06', '19:30', 'Bugle', 'Bethel A', 'Bugle Working Mens Club', 'approved'),
  ('2627-20', 'victory-league', '2026-10-06', '19:30', 'Mevagissey A', 'Luxulyan A', 'Mevagissey Social Club', 'approved'),
  ('2627-21', 'victory-league', '2026-10-06', '19:30', 'St Blazey A', 'Mevagissey B', 'St Blazey Football Club', 'approved'),
  ('2627-22', 'victory-league', '2026-10-06', '19:30', 'Tregonissey A', 'St Neot', 'Tregonissey Social Club', 'approved'),
  ('2627-23', 'victory-league', '2026-10-06', '19:30', 'Pelynt', 'St Blazey B', 'Pelynt Social Club', 'approved'),
  ('2627-24', 'rees-memorial-league', '2026-10-06', '19:30', 'Bethel D', 'Mevagissey C', 'Bethel Social Club', 'scheduled'),
  ('2627-25', 'rees-memorial-league', '2026-10-06', '19:30', 'Bethel B', 'Lerryn', 'Bethel Social Club', 'approved'),
  ('2627-26', 'rees-memorial-league', '2026-10-06', '19:30', 'Gorran Haven', 'Tregonissey B', 'Gorran Haven Snooker Club', 'approved'),
  ('2627-27', 'rees-memorial-league', '2026-10-06', '19:30', 'Luxulyan B', 'Tregonissey C', 'Luxulyan Memorial Institute', 'approved'),
  ('2627-28', 'victory-league', '2026-10-13', '19:30', 'Bethel A', 'Mevagissey B', 'Bethel Social Club', 'scheduled'),
  ('2627-29', 'victory-league', '2026-10-13', '19:30', 'St Blazey B', 'St Neot', 'St Blazey Football Club', 'scheduled'),
  ('2627-30', 'victory-league', '2026-10-13', '19:30', 'Mevagissey A', 'Bugle', 'Mevagissey Social Club', 'scheduled'),
  ('2627-31', 'victory-league', '2026-10-13', '19:30', 'Tregonissey A', 'St Blazey A', 'Tregonissey Social Club', 'scheduled'),
  ('2627-32', 'victory-league', '2026-10-13', '19:30', 'Pelynt', 'Luxulyan A', 'Pelynt Social Club', 'scheduled'),
  ('2627-33', 'rees-memorial-league', '2026-10-13', '19:30', 'Mevagissey C', 'Bethel C', 'Mevagissey Social Club', 'scheduled'),
  ('2627-34', 'rees-memorial-league', '2026-10-13', '19:30', 'Tregonissey C', 'Tregonissey B', 'Tregonissey Social Club', 'scheduled'),
  ('2627-35', 'rees-memorial-league', '2026-10-13', '19:30', 'Bethel B', 'Bethel D', 'Bethel Social Club', 'scheduled'),
  ('2627-36', 'rees-memorial-league', '2026-10-13', '19:30', 'Luxulyan B', 'Lerryn', 'Luxulyan Memorial Institute', 'scheduled'),
  ('2627-37', 'victory-league', '2026-10-27', '19:30', 'St Neot', 'Mevagissey A', 'St Neot Social Club', 'scheduled'),
  ('2627-38', 'victory-league', '2026-10-27', '19:30', 'Bugle', 'Tregonissey A', 'Bugle Working Mens Club', 'scheduled'),
  ('2627-39', 'victory-league', '2026-10-27', '19:30', 'Luxulyan A', 'Bethel A', 'Luxulyan Memorial Institute', 'scheduled'),
  ('2627-40', 'victory-league', '2026-10-27', '19:30', 'St Blazey A', 'Pelynt', 'St Blazey Football Club', 'scheduled'),
  ('2627-41', 'victory-league', '2026-10-27', '19:30', 'Mevagissey B', 'St Blazey B', 'Mevagissey Social Club', 'scheduled'),
  ('2627-42', 'rees-memorial-league', '2026-10-27', '19:30', 'Tregonissey B', 'Bethel B', 'Tregonissey Social Club', 'scheduled'),
  ('2627-43', 'rees-memorial-league', '2026-10-27', '19:30', 'Bethel D', 'Gorran Haven', 'Bethel Social Club', 'scheduled'),
  ('2627-44', 'rees-memorial-league', '2026-10-27', '19:30', 'Lerryn', 'Mevagissey C', 'Lerryn Community Centre', 'scheduled'),
  ('2627-45', 'rees-memorial-league', '2026-10-27', '19:30', 'Bethel C', 'Tregonissey C', 'Bethel Social Club', 'scheduled'),
  ('2627-46', 'victory-league', '2026-11-03', '19:30', 'St Neot', 'St Blazey A', 'St Neot Social Club', 'scheduled'),
  ('2627-47', 'victory-league', '2026-11-03', '19:30', 'Bethel A', 'Tregonissey A', 'Bethel Social Club', 'scheduled'),
  ('2627-48', 'victory-league', '2026-11-03', '19:30', 'St Blazey B', 'Bugle', 'St Blazey Football Club', 'scheduled'),
  ('2627-49', 'victory-league', '2026-11-03', '19:30', 'Mevagissey B', 'Luxulyan A', 'Mevagissey Social Club', 'scheduled'),
  ('2627-50', 'victory-league', '2026-11-03', '19:30', 'Pelynt', 'Mevagissey A', 'Pelynt Social Club', 'scheduled'),
  ('2627-51', 'rees-memorial-league', '2026-11-03', '19:30', 'Mevagissey C', 'Gorran Haven', 'Mevagissey Social Club', 'scheduled'),
  ('2627-52', 'rees-memorial-league', '2026-11-03', '19:30', 'Tregonissey C', 'Bethel D', 'Tregonissey Social Club', 'scheduled'),
  ('2627-53', 'rees-memorial-league', '2026-11-03', '19:30', 'Bethel C', 'Lerryn', 'Bethel Social Club', 'scheduled'),
  ('2627-54', 'rees-memorial-league', '2026-11-03', '19:30', 'Luxulyan B', 'Bethel B', 'Luxulyan Memorial Institute', 'scheduled'),
  ('2627-55', 'victory-league', '2026-11-10', '19:30', 'Bugle', 'Pelynt', 'Bugle Working Mens Club', 'scheduled'),
  ('2627-56', 'victory-league', '2026-11-10', '19:30', 'Luxulyan A', 'St Neot', 'Luxulyan Memorial Institute', 'scheduled'),
  ('2627-57', 'victory-league', '2026-11-10', '19:30', 'Mevagissey A', 'Mevagissey B', 'Mevagissey Social Club', 'scheduled'),
  ('2627-58', 'victory-league', '2026-11-10', '19:30', 'St Blazey A', 'Bethel A', 'St Blazey Football Club', 'scheduled'),
  ('2627-59', 'victory-league', '2026-11-10', '19:30', 'Tregonissey A', 'St Blazey B', 'Tregonissey Social Club', 'scheduled'),
  ('2627-60', 'rees-memorial-league', '2026-11-10', '19:30', 'Bethel D', 'Luxulyan B', 'Bethel Social Club', 'scheduled'),
  ('2627-61', 'rees-memorial-league', '2026-11-10', '19:30', 'Lerryn', 'Tregonissey B', 'Lerryn Community Centre', 'scheduled'),
  ('2627-62', 'rees-memorial-league', '2026-11-10', '19:30', 'Bethel B', 'Bethel C', 'Bethel Social Club', 'scheduled'),
  ('2627-63', 'rees-memorial-league', '2026-11-10', '19:30', 'Gorran Haven', 'Tregonissey C', 'Gorran Haven Snooker Club', 'scheduled'),
  ('2627-64', 'victory-league', '2026-11-17', '19:30', 'St Neot', 'Mevagissey B', 'St Neot Social Club', 'scheduled'),
  ('2627-65', 'victory-league', '2026-11-17', '19:30', 'St Blazey B', 'Bethel A', 'St Blazey Football Club', 'scheduled'),
  ('2627-66', 'victory-league', '2026-11-17', '19:30', 'Mevagissey A', 'St Blazey A', 'Mevagissey Social Club', 'scheduled'),
  ('2627-67', 'victory-league', '2026-11-17', '19:30', 'Bugle', 'Luxulyan A', 'Bugle Working Mens Club', 'scheduled'),
  ('2627-68', 'victory-league', '2026-11-17', '19:30', 'Pelynt', 'Tregonissey A', 'Pelynt Social Club', 'scheduled'),
  ('2627-69', 'rees-memorial-league', '2026-11-17', '19:30', 'Tregonissey B', 'Bethel C', 'Tregonissey Social Club', 'scheduled'),
  ('2627-70', 'rees-memorial-league', '2026-11-17', '19:30', 'Tregonissey C', 'Mevagissey C', 'Tregonissey Social Club', 'scheduled'),
  ('2627-71', 'rees-memorial-league', '2026-11-17', '19:30', 'Bethel D', 'Lerryn', 'Bethel Social Club', 'scheduled'),
  ('2627-72', 'rees-memorial-league', '2026-11-17', '19:30', 'Luxulyan B', 'Gorran Haven', 'Luxulyan Memorial Institute', 'scheduled'),
  ('2627-73', 'victory-league', '2026-12-01', '19:30', 'Bethel A', 'St Neot', 'Bethel Social Club', 'scheduled'),
  ('2627-74', 'victory-league', '2026-12-01', '19:30', 'Luxulyan A', 'St Blazey B', 'Luxulyan Memorial Institute', 'scheduled'),
  ('2627-75', 'victory-league', '2026-12-01', '19:30', 'St Blazey A', 'Bugle', 'St Blazey Football Club', 'scheduled'),
  ('2627-76', 'victory-league', '2026-12-01', '19:30', 'Tregonissey A', 'Mevagissey A', 'Tregonissey Social Club', 'scheduled'),
  ('2627-77', 'victory-league', '2026-12-01', '19:30', 'Mevagissey B', 'Pelynt', 'Mevagissey Social Club', 'scheduled'),
  ('2627-78', 'rees-memorial-league', '2026-12-01', '19:30', 'Mevagissey C', 'Tregonissey B', 'Mevagissey Social Club', 'scheduled'),
  ('2627-79', 'rees-memorial-league', '2026-12-01', '19:30', 'Lerryn', 'Tregonissey C', 'Lerryn Community Centre', 'scheduled'),
  ('2627-80', 'rees-memorial-league', '2026-12-01', '19:30', 'Gorran Haven', 'Bethel B', 'Gorran Haven Snooker Club', 'scheduled'),
  ('2627-81', 'rees-memorial-league', '2026-12-01', '19:30', 'Bethel C', 'Luxulyan B', 'Bethel Social Club', 'scheduled'),
  ('2627-82', 'victory-league', '2027-01-05', '19:30', 'Mevagissey B', 'Bugle', 'Mevagissey Social Club', 'scheduled'),
  ('2627-83', 'victory-league', '2027-01-05', '19:30', 'Bethel A', 'Mevagissey A', 'Bethel Social Club', 'scheduled'),
  ('2627-84', 'victory-league', '2027-01-05', '19:30', 'St Blazey B', 'St Blazey A', 'St Blazey Football Club', 'scheduled'),
  ('2627-85', 'victory-league', '2027-01-05', '19:30', 'Luxulyan A', 'Tregonissey A', 'Luxulyan Memorial Institute', 'scheduled'),
  ('2627-86', 'victory-league', '2027-01-05', '19:30', 'St Neot', 'Pelynt', 'St Neot Social Club', 'scheduled'),
  ('2627-87', 'rees-memorial-league', '2027-01-05', '19:30', 'Bethel C', 'Bethel D', 'Bethel Social Club', 'scheduled'),
  ('2627-88', 'rees-memorial-league', '2027-01-05', '19:30', 'Mevagissey C', 'Bethel B', 'Mevagissey Social Club', 'scheduled'),
  ('2627-89', 'rees-memorial-league', '2027-01-05', '19:30', 'Lerryn', 'Gorran Haven', 'Lerryn Community Centre', 'scheduled'),
  ('2627-90', 'rees-memorial-league', '2027-01-05', '19:30', 'Tregonissey B', 'Luxulyan B', 'Tregonissey Social Club', 'scheduled'),
  ('2627-91', 'victory-league', '2027-01-12', '19:30', 'Bugle', 'St Neot', 'Bugle Working Mens Club', 'scheduled'),
  ('2627-92', 'victory-league', '2027-01-12', '19:30', 'Pelynt', 'Bethel A', 'Pelynt Social Club', 'scheduled'),
  ('2627-93', 'victory-league', '2027-01-12', '19:30', 'Mevagissey A', 'St Blazey B', 'Mevagissey Social Club', 'scheduled'),
  ('2627-94', 'victory-league', '2027-01-12', '19:30', 'St Blazey A', 'Luxulyan A', 'St Blazey Football Club', 'scheduled'),
  ('2627-95', 'victory-league', '2027-01-12', '19:30', 'Tregonissey A', 'Mevagissey B', 'Tregonissey Social Club', 'scheduled'),
  ('2627-96', 'rees-memorial-league', '2027-01-12', '19:30', 'Bethel D', 'Tregonissey B', 'Bethel Social Club', 'scheduled'),
  ('2627-97', 'rees-memorial-league', '2027-01-12', '19:30', 'Luxulyan B', 'Mevagissey C', 'Luxulyan Memorial Institute', 'scheduled'),
  ('2627-98', 'rees-memorial-league', '2027-01-12', '19:30', 'Bethel B', 'Tregonissey C', 'Bethel Social Club', 'scheduled'),
  ('2627-99', 'rees-memorial-league', '2027-01-12', '19:30', 'Gorran Haven', 'Bethel C', 'Gorran Haven Snooker Club', 'scheduled'),
  ('2627-100', 'victory-league', '2027-01-19', '19:30', 'Bethel A', 'Bugle', 'Bethel Social Club', 'scheduled'),
  ('2627-101', 'victory-league', '2027-01-19', '19:30', 'Luxulyan A', 'Mevagissey A', 'Luxulyan Memorial Institute', 'scheduled'),
  ('2627-102', 'victory-league', '2027-01-19', '19:30', 'Mevagissey B', 'St Blazey A', 'Mevagissey Social Club', 'scheduled'),
  ('2627-103', 'victory-league', '2027-01-19', '19:30', 'St Neot', 'Tregonissey A', 'St Neot Social Club', 'scheduled'),
  ('2627-104', 'victory-league', '2027-01-19', '19:30', 'St Blazey B', 'Pelynt', 'St Blazey Football Club', 'scheduled'),
  ('2627-105', 'rees-memorial-league', '2027-01-19', '19:30', 'Mevagissey C', 'Bethel D', 'Mevagissey Social Club', 'scheduled'),
  ('2627-106', 'rees-memorial-league', '2027-01-19', '19:30', 'Lerryn', 'Bethel B', 'Lerryn Community Centre', 'scheduled'),
  ('2627-107', 'rees-memorial-league', '2027-01-19', '19:30', 'Tregonissey B', 'Gorran Haven', 'Tregonissey Social Club', 'scheduled'),
  ('2627-108', 'rees-memorial-league', '2027-01-19', '19:30', 'Tregonissey C', 'Luxulyan B', 'Tregonissey Social Club', 'scheduled'),
  ('2627-109', 'victory-league', '2027-02-02', '19:30', 'Mevagissey B', 'Bethel A', 'Mevagissey Social Club', 'scheduled'),
  ('2627-110', 'victory-league', '2027-02-02', '19:30', 'St Neot', 'St Blazey B', 'St Neot Social Club', 'scheduled'),
  ('2627-111', 'victory-league', '2027-02-02', '19:30', 'Bugle', 'Mevagissey A', 'Bugle Working Mens Club', 'scheduled'),
  ('2627-112', 'victory-league', '2027-02-02', '19:30', 'St Blazey A', 'Tregonissey A', 'St Blazey Football Club', 'scheduled'),
  ('2627-113', 'victory-league', '2027-02-02', '19:30', 'Luxulyan A', 'Pelynt', 'Luxulyan Memorial Institute', 'scheduled'),
  ('2627-114', 'rees-memorial-league', '2027-02-02', '19:30', 'Bethel C', 'Mevagissey C', 'Bethel Social Club', 'scheduled'),
  ('2627-115', 'rees-memorial-league', '2027-02-02', '19:30', 'Tregonissey B', 'Tregonissey C', 'Tregonissey Social Club', 'scheduled'),
  ('2627-116', 'rees-memorial-league', '2027-02-02', '19:30', 'Bethel D', 'Bethel B', 'Bethel Social Club', 'scheduled'),
  ('2627-117', 'rees-memorial-league', '2027-02-02', '19:30', 'Lerryn', 'Luxulyan B', 'Lerryn Community Centre', 'scheduled'),
  ('2627-118', 'victory-league', '2027-02-09', '19:30', 'Mevagissey A', 'St Neot', 'Mevagissey Social Club', 'scheduled'),
  ('2627-119', 'victory-league', '2027-02-09', '19:30', 'Tregonissey A', 'Bugle', 'Tregonissey Social Club', 'scheduled'),
  ('2627-120', 'victory-league', '2027-02-09', '19:30', 'Bethel A', 'Luxulyan A', 'Bethel Social Club', 'scheduled'),
  ('2627-121', 'victory-league', '2027-02-09', '19:30', 'Pelynt', 'St Blazey A', 'Pelynt Social Club', 'scheduled'),
  ('2627-122', 'victory-league', '2027-02-09', '19:30', 'St Blazey B', 'Mevagissey B', 'St Blazey Football Club', 'scheduled'),
  ('2627-123', 'rees-memorial-league', '2027-02-09', '19:30', 'Bethel B', 'Tregonissey B', 'Bethel Social Club', 'scheduled'),
  ('2627-124', 'rees-memorial-league', '2027-02-09', '19:30', 'Gorran Haven', 'Bethel D', 'Gorran Haven Snooker Club', 'scheduled'),
  ('2627-125', 'rees-memorial-league', '2027-02-09', '19:30', 'Mevagissey C', 'Lerryn', 'Mevagissey Social Club', 'scheduled'),
  ('2627-126', 'rees-memorial-league', '2027-02-09', '19:30', 'Tregonissey C', 'Bethel C', 'Tregonissey Social Club', 'scheduled'),
  ('2627-127', 'victory-league', '2027-02-23', '19:30', 'St Blazey A', 'St Neot', 'St Blazey Football Club', 'scheduled'),
  ('2627-128', 'victory-league', '2027-02-23', '19:30', 'Tregonissey A', 'Bethel A', 'Tregonissey Social Club', 'scheduled'),
  ('2627-129', 'victory-league', '2027-02-23', '19:30', 'Bugle', 'St Blazey B', 'Bugle Working Mens Club', 'scheduled'),
  ('2627-130', 'victory-league', '2027-02-23', '19:30', 'Luxulyan A', 'Mevagissey B', 'Luxulyan Memorial Institute', 'scheduled'),
  ('2627-131', 'victory-league', '2027-02-23', '19:30', 'Mevagissey A', 'Pelynt', 'Mevagissey Social Club', 'scheduled'),
  ('2627-132', 'rees-memorial-league', '2027-02-23', '19:30', 'Gorran Haven', 'Mevagissey C', 'Gorran Haven Snooker Club', 'scheduled'),
  ('2627-133', 'rees-memorial-league', '2027-02-23', '19:30', 'Bethel D', 'Tregonissey C', 'Bethel Social Club', 'scheduled'),
  ('2627-134', 'rees-memorial-league', '2027-02-23', '19:30', 'Lerryn', 'Bethel C', 'Lerryn Community Centre', 'scheduled'),
  ('2627-135', 'rees-memorial-league', '2027-02-23', '19:30', 'Bethel B', 'Luxulyan B', 'Bethel Social Club', 'scheduled'),
  ('2627-136', 'victory-league', '2027-03-02', '19:30', 'Pelynt', 'Bugle', 'Pelynt Social Club', 'scheduled'),
  ('2627-137', 'victory-league', '2027-03-02', '19:30', 'St Neot', 'Luxulyan A', 'St Neot Social Club', 'scheduled'),
  ('2627-138', 'victory-league', '2027-03-02', '19:30', 'Mevagissey B', 'Mevagissey A', 'Mevagissey Social Club', 'scheduled'),
  ('2627-139', 'victory-league', '2027-03-02', '19:30', 'Bethel A', 'St Blazey A', 'Bethel Social Club', 'scheduled'),
  ('2627-140', 'victory-league', '2027-03-02', '19:30', 'St Blazey B', 'Tregonissey A', 'St Blazey Football Club', 'scheduled'),
  ('2627-141', 'rees-memorial-league', '2027-03-02', '19:30', 'Luxulyan B', 'Bethel D', 'Luxulyan Memorial Institute', 'scheduled'),
  ('2627-142', 'rees-memorial-league', '2027-03-02', '19:30', 'Tregonissey B', 'Lerryn', 'Tregonissey Social Club', 'scheduled'),
  ('2627-143', 'rees-memorial-league', '2027-03-02', '19:30', 'Bethel C', 'Bethel B', 'Bethel Social Club', 'scheduled'),
  ('2627-144', 'rees-memorial-league', '2027-03-02', '19:30', 'Tregonissey C', 'Gorran Haven', 'Tregonissey Social Club', 'scheduled'),
  ('2627-145', 'victory-league', '2027-03-09', '19:30', 'Mevagissey B', 'St Neot', 'Mevagissey Social Club', 'scheduled'),
  ('2627-146', 'victory-league', '2027-03-09', '19:30', 'Bethel A', 'St Blazey B', 'Bethel Social Club', 'scheduled'),
  ('2627-147', 'victory-league', '2027-03-09', '19:30', 'St Blazey A', 'Mevagissey A', 'St Blazey Football Club', 'scheduled'),
  ('2627-148', 'victory-league', '2027-03-09', '19:30', 'Luxulyan A', 'Bugle', 'Luxulyan Memorial Institute', 'scheduled'),
  ('2627-149', 'victory-league', '2027-03-09', '19:30', 'Tregonissey A', 'Pelynt', 'Tregonissey Social Club', 'scheduled'),
  ('2627-150', 'rees-memorial-league', '2027-03-09', '19:30', 'Bethel C', 'Tregonissey B', 'Bethel Social Club', 'scheduled'),
  ('2627-151', 'rees-memorial-league', '2027-03-09', '19:30', 'Mevagissey C', 'Tregonissey C', 'Mevagissey Social Club', 'scheduled'),
  ('2627-152', 'rees-memorial-league', '2027-03-09', '19:30', 'Lerryn', 'Bethel D', 'Lerryn Community Centre', 'scheduled'),
  ('2627-153', 'rees-memorial-league', '2027-03-09', '19:30', 'Gorran Haven', 'Luxulyan B', 'Gorran Haven Snooker Club', 'scheduled'),
  ('2627-154', 'victory-league', '2027-03-16', '19:30', 'St Neot', 'Bethel A', 'St Neot Social Club', 'scheduled'),
  ('2627-155', 'victory-league', '2027-03-16', '19:30', 'St Blazey B', 'Luxulyan A', 'St Blazey Football Club', 'scheduled'),
  ('2627-156', 'victory-league', '2027-03-16', '19:30', 'Bugle', 'St Blazey A', 'Bugle Working Mens Club', 'scheduled'),
  ('2627-157', 'victory-league', '2027-03-16', '19:30', 'Mevagissey A', 'Tregonissey A', 'Mevagissey Social Club', 'scheduled'),
  ('2627-158', 'victory-league', '2027-03-16', '19:30', 'Pelynt', 'Mevagissey B', 'Pelynt Social Club', 'scheduled'),
  ('2627-159', 'rees-memorial-league', '2027-03-16', '19:30', 'Tregonissey B', 'Mevagissey C', 'Tregonissey Social Club', 'scheduled'),
  ('2627-160', 'rees-memorial-league', '2027-03-16', '19:30', 'Tregonissey C', 'Lerryn', 'Tregonissey Social Club', 'scheduled'),
  ('2627-161', 'rees-memorial-league', '2027-03-16', '19:30', 'Bethel B', 'Gorran Haven', 'Bethel Social Club', 'scheduled'),
  ('2627-162', 'rees-memorial-league', '2027-03-16', '19:30', 'Luxulyan B', 'Bethel C', 'Luxulyan Memorial Institute', 'scheduled');
insert into fixtures (season_id, league_id, home_team_id, away_team_id, venue_id, starts_at, status, code)
  select s.id, l.id, h.id, a.id, v.id, (r.day + r.kick_off) at time zone 'Europe/London', r.status, r.code
  from _fixtures r
  join seasons s on s.name = '2026-2027' join leagues l on l.slug = r.league_slug
  join teams h on lower(h.name) = lower(r.home) join teams a on lower(a.name) = lower(r.away)
  left join venues v on lower(v.name) = lower(r.venue)
  order by r.code;

-- Bye weeks (the Rees Memorial League has nine teams, so one sits out each match night).
create temp table _byes (league_slug text, team text, day date) on commit drop;
insert into _byes values
  ('rees-memorial-league', 'Tregonissey C', '2026-09-22'),
  ('rees-memorial-league', 'Lerryn', '2026-09-29'),
  ('rees-memorial-league', 'Bethel C', '2026-10-06'),
  ('rees-memorial-league', 'Gorran Haven', '2026-10-13'),
  ('rees-memorial-league', 'Luxulyan B', '2026-10-27'),
  ('rees-memorial-league', 'Tregonissey B', '2026-11-03'),
  ('rees-memorial-league', 'Mevagissey C', '2026-11-10'),
  ('rees-memorial-league', 'Bethel B', '2026-11-17'),
  ('rees-memorial-league', 'Bethel D', '2026-12-01'),
  ('rees-memorial-league', 'Tregonissey C', '2027-01-05'),
  ('rees-memorial-league', 'Lerryn', '2027-01-12'),
  ('rees-memorial-league', 'Bethel C', '2027-01-19'),
  ('rees-memorial-league', 'Gorran Haven', '2027-02-02'),
  ('rees-memorial-league', 'Luxulyan B', '2027-02-09'),
  ('rees-memorial-league', 'Tregonissey B', '2027-02-23'),
  ('rees-memorial-league', 'Mevagissey C', '2027-03-02'),
  ('rees-memorial-league', 'Bethel B', '2027-03-09'),
  ('rees-memorial-league', 'Bethel D', '2027-03-16');
insert into byes (season_id, league_id, team_id, bye_on)
  select s.id, l.id, t.id, r.day from _byes r
  join seasons s on s.name = '2026-2027' join leagues l on l.slug = r.league_slug join teams t on lower(t.name) = lower(r.team);

-- ── 6. the scorecards played so far ───────────────────────────
-- A player with ext = true played that frame as the team's extra player; no name = an unnamed stand-in.
create temp table _frames (code text, frame_no int, home_player text, home_ext boolean, home_points int, away_player text, away_ext boolean, away_points int) on commit drop;
insert into _frames values
  ('2627-01', 1, 'Ian Ball', false, 38, 'Ben Rothwell', false, 53),
  ('2627-01', 2, 'Keith Moore', false, 63, 'Dave Kendall', false, 29),
  ('2627-01', 3, 'Jake Moore', false, 38, 'Nathan Shaw', false, 51),
  ('2627-01', 4, 'Dave Rundle', false, 19, 'Pete Chambers', false, 69),
  ('2627-01', 5, 'Mark Sturtridge', false, 52, 'Ben Rothwell', true, 62),
  ('2627-02', 1, 'Ryan Bilson', false, 35, 'Matt Green', false, 55),
  ('2627-02', 2, 'Charlie Prynn', false, 41, 'Paul Baron', false, 53),
  ('2627-02', 3, 'Matthew Chesterfield', false, 49, 'Garry Stephens', false, 73),
  ('2627-02', 4, 'Ben Prynn', false, 48, 'Andy Peers', false, 38),
  ('2627-02', 5, 'Matt Mills', false, 62, 'Mark Ashton', false, 61),
  ('2627-03', 1, 'George Taylor', false, 14, 'Gavin Dyche', false, 54),
  ('2627-03', 2, 'Kyle Masters', false, 43, 'Clive Stuthridge', false, 47),
  ('2627-03', 3, 'Darren Roberts', false, 65, 'Ryan Orchard', false, 46),
  ('2627-03', 4, 'Chris Brown', false, 15, 'Ian Millward', false, 60),
  ('2627-03', 5, 'Stuart Dewings', false, 26, 'Joshua Bristow', false, 54),
  ('2627-04', 1, 'Kevin Harris', false, 31, 'Justin Oxenham', false, 51),
  ('2627-04', 2, 'Mark Poulson', false, 67, 'Harrison Burdon', false, 44),
  ('2627-04', 3, 'Andrew Gooch', false, 48, 'Andrew Best', false, 12),
  ('2627-04', 4, 'Jason Cocks', false, 73, 'Simon Taylor', false, 38),
  ('2627-04', 5, 'Geoff Merriman', false, 24, 'Gary Spencer', false, 59),
  ('2627-05', 1, 'Phil Ormond', false, 55, 'Darren OShea', false, 11),
  ('2627-05', 2, 'Paul Woodman', false, 63, 'Chris Perring', false, 50),
  ('2627-05', 3, 'Richard Broad', false, 43, 'Anthony Maddams', false, 24),
  ('2627-05', 4, 'Len Flower', false, 7, 'Darran Lock', false, 87),
  ('2627-05', 5, 'Jamie Daniell', false, 41, 'Steve Courts', false, 62),
  ('2627-10', 1, 'Darren OShea', false, 21, 'Keith Moore', false, 43),
  ('2627-10', 2, 'Mark Nicolas', false, 51, 'Dave Rundle', false, 39),
  ('2627-10', 3, 'Steve Courts', false, 45, 'Jake Moore', false, 67),
  ('2627-10', 4, 'Chris Perring', false, 40, 'Ian Ball', false, 76),
  ('2627-10', 5, 'Darran Lock', false, 75, 'Mark Sturtridge', false, 29),
  ('2627-11', 1, 'Garry Stephens', false, 52, 'John Daniell', false, 10),
  ('2627-11', 2, 'Paul Baron', false, 55, 'Jamie Daniell', false, 37),
  ('2627-11', 3, 'Andy Peers', false, 66, 'Len Flower', false, 21),
  ('2627-11', 4, 'Matt Green', false, 50, 'Richard Broad', false, 15),
  ('2627-11', 5, 'Mark Ashton', false, 46, 'Phil Ormond', false, 52),
  ('2627-12', 1, 'Gavin Dyche', false, 30, 'Ryan Bilson', false, 62),
  ('2627-12', 2, 'Ryan Orchard', false, 60, 'Charlie Prynn', false, 32),
  ('2627-12', 3, 'Ian Millward', false, 64, 'Ben Prynn', false, 24),
  ('2627-12', 4, 'Joshua Bristow', false, 69, 'Matt Mills', false, 53),
  ('2627-12', 5, 'Clive Stuthridge', false, 51, 'Matthew Chesterfield', false, 66),
  ('2627-13', 1, 'Gary Spencer', false, 68, 'Stuart Dewings', false, 1),
  ('2627-13', 2, 'Justin Oxenham', false, 44, 'George Taylor', false, 52),
  ('2627-13', 3, 'Harrison Burdon', false, 49, 'Chris Brown', false, 36),
  ('2627-13', 4, 'Simon Taylor', false, 17, 'Martin Richards', false, 62),
  ('2627-13', 5, 'Andrew Best', false, 85, 'Darren Roberts', false, 6),
  ('2627-14', 1, 'Ben Rothwell', false, 33, 'Jason Cocks', false, 55),
  ('2627-14', 2, 'Dave Kendall', false, 55, 'Kevin Harris', false, 24),
  ('2627-14', 3, 'Nathan Shaw', false, 27, 'Mark Poulson', false, 51),
  ('2627-14', 4, 'Mark Gregory', false, 30, 'Geoff Merriman', false, 57),
  ('2627-14', 5, 'Matt Rowe', false, 25, 'Andrew Gooch', false, 73),
  ('2627-19', 1, 'Jake Moore', false, 61, 'Andy Peers', false, 17),
  ('2627-19', 2, 'Keith Moore', false, 54, 'Matt Green', false, 44),
  ('2627-19', 3, 'Mark Sturtridge', false, 11, 'Mark Ashton', false, 72),
  ('2627-19', 4, 'Colin Rundle', false, 16, 'Garry Stephens', false, 56),
  ('2627-19', 5, 'Dave Rundle', false, 13, 'Paul Baron', false, 86),
  ('2627-20', 1, 'Matthew Chesterfield', false, 51, 'Andrew Best', false, 48),
  ('2627-20', 2, 'Matt Mills', false, 28, 'Gary Spencer', false, 65),
  ('2627-20', 3, 'Ryan Bilson', false, 63, 'Simon Taylor', false, 10),
  ('2627-20', 4, 'Ben Prynn', false, 33, 'Harrison Burdon', false, 54),
  ('2627-20', 5, 'Charlie Prynn', false, 23, 'Justin Oxenham', false, 52),
  ('2627-21', 1, 'Stuart Dewings', false, 46, 'Dave Kendall', false, 32),
  ('2627-21', 2, 'Chris Brown', false, 46, 'Ben Rothwell', false, 57),
  ('2627-21', 3, 'George Taylor', false, 34, 'Mark Gregory', false, 63),
  ('2627-21', 4, 'Darren Roberts', false, 40, 'Nathan Shaw', false, 56),
  ('2627-21', 5, 'Martin Richards', false, 21, 'Matt Rowe', false, 45),
  ('2627-22', 1, 'Jason Cocks', false, 72, 'Steve Courts', false, 27),
  ('2627-22', 2, 'Kevin Harris', false, 52, 'Anthony Maddams', false, 11),
  ('2627-22', 3, 'Mark Poulson', false, 28, 'Darran Lock', false, 50),
  ('2627-22', 4, 'Geoff Merriman', false, 66, 'Chris Perring', false, 61),
  ('2627-22', 5, 'Andrew Gooch', false, 68, 'Darren OShea', false, 26),
  ('2627-23', 1, 'Paul Woodman', false, 54, 'Clive Stuthridge', false, 29),
  ('2627-23', 2, 'Jamie Daniell', false, 66, 'Ian Millward', false, 22),
  ('2627-23', 3, 'Phil Ormond', false, 52, 'Gavin Dyche', false, 31),
  ('2627-23', 4, 'Len Flower', false, 54, 'Ryan Orchard', false, 35),
  ('2627-23', 5, 'Richard Broad', false, 15, 'Joshua Bristow', false, 61),
  ('2627-06', 1, 'Bob Stephens', false, 59, 'Howard Brett', false, 26),
  ('2627-06', 2, 'Steve Bennallack', false, 60, 'Mike Haley', false, 35),
  ('2627-06', 3, 'Geoff Hawken', false, 26, 'James Smithson', false, 46),
  ('2627-06', 4, 'Jason Pascoe', false, 58, 'Leigh Rosevear', false, 16),
  ('2627-06', 5, 'Andy Sayer', false, 53, 'Paul Smithson', false, 32),
  ('2627-07', 1, 'Matt Moore', false, 41, 'Glyn Tamblin', false, 10),
  ('2627-07', 2, 'Mark Haworth', false, 36, 'Adrian Evans', false, 52),
  ('2627-07', 3, 'Craig Nicholls', false, 4, 'Richard Tamblin', false, 54),
  ('2627-07', 4, 'Darren Biggen', false, 52, 'Oliver Watson', false, 44),
  ('2627-07', 5, 'Roy Bayliss', false, 1, 'Andrew Kitt', false, 0),
  ('2627-08', 1, 'James Towsey', false, 65, 'Les Shakespeare', false, 10),
  ('2627-08', 2, 'Rob Bunney', false, 40, 'Terry Middleton', false, 47),
  ('2627-08', 3, 'Lee McKinstry', false, 63, 'Simon Yeo', false, 39),
  ('2627-08', 4, 'Steve Williams', false, 40, 'John Hancock', false, 10),
  ('2627-08', 5, 'Matt Fox', false, 52, null, true, 27),
  ('2627-09', 1, 'Simon Johnson', false, 50, 'Chris Witcombe', false, 9),
  ('2627-09', 2, 'Keith Remphry', false, 41, 'Jowan Truman', false, 34),
  ('2627-09', 3, 'Kevin Spencer', false, 49, 'Nathan Taylor', false, 35),
  ('2627-09', 4, 'Steve Vicary', false, 62, 'Ryan Taylor', false, 31),
  ('2627-09', 5, 'Kyle Bennetts', false, 55, null, true, 22),
  ('2627-15', 1, 'Chris Witcombe', false, 35, 'Jason Pascoe', false, 45),
  ('2627-15', 2, 'Ryan Taylor', false, 70, 'Steve Bennallack', false, 27),
  ('2627-15', 3, 'Nathan Taylor', false, 37, 'Bob Stephens', false, 53),
  ('2627-15', 4, 'Marc Luczynski', false, 43, 'Andy Sayer', false, 53),
  ('2627-15', 5, 'Mark Craddock', false, 48, 'Geoff Hawken', false, 63),
  ('2627-16', 1, 'Oliver Watson', false, 15, 'Kyle Bennetts', false, 56),
  ('2627-16', 2, 'Glyn Tamblin', false, 5, 'Chris Austin', false, 48),
  ('2627-16', 3, 'Adrian Evans', false, 56, 'Steve Vicary', false, 54),
  ('2627-16', 4, 'Richard Tamblin', false, 58, 'Keith Remphry', false, 16),
  ('2627-16', 5, 'Oliver Watson', true, 58, 'Kevin Spencer', false, 38),
  ('2627-17', 1, 'Darren Elliott', false, 37, 'Craig Nicholls', false, 51),
  ('2627-17', 2, 'Amanda Fleming', false, 20, 'Roy Bayliss', false, 63),
  ('2627-17', 3, 'Mark Richards', false, 66, 'Matt Moore', false, 31),
  ('2627-17', 4, 'Lucy Harrison', false, 15, 'Terry Nicholls', false, 40),
  ('2627-17', 5, 'Kelly McMullen', false, 27, 'Darren Biggen', false, 47),
  ('2627-18', 1, 'Howard Brett', false, 53, 'Lee McKinstry', false, 43),
  ('2627-18', 2, 'Paul Smithson', false, 57, 'Rob Bunney', false, 40),
  ('2627-18', 3, 'James Smithson', false, 9, 'James Towsey', false, 42),
  ('2627-18', 4, 'Leigh Rosevear', false, 51, 'Steve Williams', false, 32),
  ('2627-18', 5, 'Ben Stunell', false, 18, 'Matt Fox', false, 60),
  ('2627-25', 1, 'Mark Haworth', false, 38, 'James Stephens', false, 49),
  ('2627-25', 2, 'Roy Bayliss', false, 45, 'Terry Middleton', false, 14),
  ('2627-25', 3, 'Craig Nicholls', false, 63, 'John Hancock', false, 23),
  ('2627-25', 4, 'Matt Moore', false, 16, 'Les Shakespeare', false, 60),
  ('2627-25', 5, 'Darren Biggen', false, 58, 'Simon Yeo', false, 7),
  ('2627-26', 1, 'Steve Williams', false, 26, 'Nathan Taylor', false, 54),
  ('2627-26', 2, 'James Towsey', false, 32, 'Chris Witcombe', false, 49),
  ('2627-26', 3, 'Rob Bunney', false, 65, 'Ryan Taylor', false, 71),
  ('2627-26', 4, 'Lee McKinstry', false, 36, 'Marc Luczynski', false, 54),
  ('2627-26', 5, 'Matt Fox', false, 59, 'Jowan Truman', false, 16),
  ('2627-27', 1, 'Kyle Bennetts', false, 46, 'Ellie Potter', false, 27),
  ('2627-27', 2, 'Simon Johnson', false, 76, 'Martin Richards', false, 48),
  ('2627-27', 3, 'Steve Vicary', false, 57, 'Amanda Fleming', false, 34),
  ('2627-27', 4, 'Keith Remphry', false, 76, 'Kelly McMullen', false, 43),
  ('2627-27', 5, 'Kevin Spencer', false, 48, 'Darren Elliott', false, 30);
insert into frames (fixture_id, frame_no, home_player_id, away_player_id, home_points, away_points, home_ext, away_ext)
  select f.id, r.frame_no, hp.id, ap.id, r.home_points, r.away_points, r.home_ext, r.away_ext
  from _frames r join fixtures f on f.code = r.code
  left join players hp on lower(hp.full_name) = lower(r.home_player)
  left join players ap on lower(ap.full_name) = lower(r.away_player);

create temp table _breaks (code text, frame_no int, player text, value int) on commit drop;
insert into _breaks values
  ('2627-02', 5, 'Mark Ashton', 34),
  ('2627-04', 4, 'Jason Cocks', 32),
  ('2627-10', 3, 'Jake Moore', 32),
  ('2627-12', 3, 'Ian Millward', 33),
  ('2627-19', 5, 'Paul Baron', 45),
  ('2627-20', 3, 'Ryan Bilson', 41),
  ('2627-21', 2, 'Chris Brown', 31),
  ('2627-22', 1, 'Jason Cocks', 48),
  ('2627-23', 2, 'Jamie Daniell', 34),
  ('2627-23', 5, 'Joshua Bristow', 30);
insert into breaks (fixture_id, frame_no, player_id, value)
  select f.id, r.frame_no, p.id, r.value from _breaks r join fixtures f on f.code = r.code join players p on lower(p.full_name) = lower(r.player);

-- ── 7. the competitions of 2026-2027 (no draws yet) ───────────
create temp table _competitions (name text, kind text, handicap boolean, best_of int, rees_only boolean, info text, sort int) on commit drop;
insert into _competitions values
  ('Team Handicap', 'Team', true, 5, false, 'To be played on Tuesday 20th October.', 1),
  ('Rees Singles', 'Singles', false, 5, true, 'Home player to contact by 30th October. Games to be played by 30th December.', 2),
  ('Shootout', 'Singles', false, 1, false, null, 3),
  ('Bill Toms', 'Singles', true, 5, false, 'Home player to contact by 16th October. Games to be played by 6th November. Away player receives 5 extra points.', 4),
  ('Seniors', 'Singles', true, 5, false, 'Home player to contact by 16th October. Games to be played by 6th November. Away player receives 5 extra points.', 5),
  ('Willie Thomas', 'Singles', true, 5, false, 'Home player to contact by 30th October. Games to be played by 30th December. Away player receives 5 extra points.', 6),
  ('Doubles', 'Doubles', false, 5, false, 'Home player to contact by 30th October. Games to be played by 30th December.', 7),
  ('Singles', 'Singles', false, 5, false, 'Home player to contact by 16th October. Games to be played by 6th November.', 8),
  ('Handicap Doubles', 'Doubles', true, 5, false, 'Home player to contact by 30th October. Games to be played by 30th December.', 9),
  ('Team Pairs', 'Doubles', false, 5, false, null, 10),
  ('GB Trophy', 'Other', false, 5, false, null, 11);
-- Sample competitions the league doesn't run (the sample plate, for one) go.
delete from competitions c where c.id::text like '00000000-0000-4000-8000-%' and not exists (select 1 from _competitions r where lower(r.name) = lower(c.name));
-- The ones already there keep their pictures, trophies and entry-form settings; the sample draw record,
-- notes and round dates they came with are replaced.
update competitions c set kind = r.kind, handicap = r.handicap, best_of = r.best_of, sort = r.sort, draw_live = null,
    league_ids = case when r.rees_only then (select jsonb_build_array(id) from leagues where slug = 'rees-memorial-league') else '[]'::jsonb end,
    info = case when c.info is null or c.info like '%Placeholder text%' then r.info else c.info end,
    round_deadlines = case when c.id::text like '00000000-0000-4000-8000-%' then '{}'::jsonb else c.round_deadlines end
  from _competitions r where lower(c.name) = lower(r.name);
insert into competitions (name, slug, season_id, kind, handicap, best_of, info, sort, league_ids)
  select r.name, public.slugify(r.name), (select id from seasons where name = '2026-2027'), r.kind, r.handicap, r.best_of, r.info, r.sort,
    case when r.rees_only then (select jsonb_build_array(id) from leagues where slug = 'rees-memorial-league') else '[]'::jsonb end
  from _competitions r where not exists (select 1 from competitions c where lower(c.name) = lower(r.name));

-- ── 8. check it all arrived, or change nothing ────────────────
do $$
declare n int;
begin
  select count(*) into n from fixtures;
  if n <> 162 then raise exception 'Expected 162 fixtures, found %. Nothing has been changed.', n; end if;
  select count(*) into n from frames;
  if n <> 130 then raise exception 'Expected 130 frames, found % (is a player in the database twice under the same name?). Nothing has been changed.', n; end if;
  select count(*) into n from breaks;
  if n <> 10 then raise exception 'Expected 10 breaks, found %. Nothing has been changed.', n; end if;
  select count(*) into n from byes;
  if n <> 18 then raise exception 'Expected 18 bye weeks, found %. Nothing has been changed.', n; end if;
  select count(*) into n from _frames r
    where (r.home_player is not null and not exists (select 1 from players p where lower(p.full_name) = lower(r.home_player)))
       or (r.away_player is not null and not exists (select 1 from players p where lower(p.full_name) = lower(r.away_player)));
  if n <> 0 then raise exception '% frames name a player who is not in the players list. Nothing has been changed.', n; end if;
  select count(*) into n from _players r where not exists (select 1 from players p where lower(p.full_name) = lower(r.full_name));
  if n <> 0 then raise exception '% players did not arrive. Nothing has been changed.', n; end if;
  select count(*) into n from players p join teams t on t.id = p.team_id where p.status = 'playing';
  raise notice 'Done: % players in teams, % fixtures, % frames, % breaks, % bye weeks.', n,
    (select count(*) from fixtures), (select count(*) from frames), (select count(*) from breaks), (select count(*) from byes);
end $$;

commit;
